name: "Build and Cache"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 3 * * *' # Every night at 3:00 AM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        # This ensures flakes are enabled and nixpkgs is mapped correctly
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: cmspam  # <--- DOUBLE CHECK THIS NAME
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Update nixpkgs
      run: nix flake update

    - name: Build QEMU
      # Building .#default is correct as per your flake.nix
      run: nix build .#default --print-build-logs
