name: "Build and Cache"
on:
  pull_request:
  push:
  schedule:
    - cron: '0 3 * * *' # Every night at 3:00 AM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: qemu-patched # Your cache name
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    # This updates the flake lock to the latest nixpkgs before building
    - name: Update nixpkgs
      run: nix flake update

    - name: Build QEMU
      run: nix build .#default
